### ISSUE TITLE
Question or enhancement idea

### ISSUE THREAD

**Issue by rcortez-la** [derpenstiltskin/connectwise-powerbi#2]
Nice work. This is great stuff.

Is there a way to set the condition to the date buried in the _info record?  dateEntered
I'm looking for a way to GET data from a date in the past going forward, vs the entire CW dataset.

**Comment by derpenstiltskin** [comment]
What endpoint are you trying to query? I looked at the output from the service/tickets endpoint and all of the children with _info children just contain hyperlinks.

**Comment by rcortez-la** [comment]
> What endpoint are you trying to query? I looked at the output from the service/tickets endpoint and all of the children with _info children just contain hyperlinks.

The same service/tickets. Our tenant has a few additional have lastUpdated, updatedBy, dateEntered, enteredBy.  I'm a rooky with CW, and maybe these are unique on this tenant.  What I'm looking for is the created date of the ticket. I was told by the business owner dateEntered is the field I need.

**Comment by derpenstiltskin** [comment]
My bad I totally missed the root _info in the API response last night. I just tested this in Postman and should work. The following conditions worked for me:
`_info/dateEntered > [2016-08-20T18:04:26Z]`

In the ConnectWise Manage API you can access sub-object attributes with the syntax of subobject/attribute. If the attribute is in a child array you need to use childConditions instead of conditions. To be able to filter with dates they have to be in ISO8601 format and surrounded by square brackets.

**Comment by derpenstiltskin** [comment]
> The same service/tickets. Our tenant has a few additional have lastUpdated, updatedBy, dateEntered, enteredBy. I'm a rooky with CW, and maybe these are unique on this tenant. What I'm looking for is the created date of the ticket. I was told by the business owner dateEntered is the field I need.

My bad I totally missed the root _info in the API response last night. I just tested this in Postman and should work. The following conditions worked for me:
`_info/dateEntered > [2016-08-20T18:04:26Z]`

In the ConnectWise Manage API you can access sub-object attributes with the syntax of subobject/attribute. If the attribute is in a child array you need to use childConditions instead of conditions. To be able to filter with dates they have to be in ISO8601 format and surrounded by square brackets.

**Comment by rcortez-la** [comment]
> > The same service/tickets. Our tenant has a few additional have lastUpdated, updatedBy, dateEntered, enteredBy. I'm a rooky with CW, and maybe these are unique on this tenant. What I'm looking for is the created date of the ticket. I was told by the business owner dateEntered is the field I need.
> 
> My bad I totally missed the root _info in the API response last night. I just tested this in Postman and should work. The following conditions worked for me: `_info/dateEntered > [2016-08-20T18:04:26Z]`
> 
> In the ConnectWise Manage API you can access sub-object attributes with the syntax of subobject/attribute. If the attribute is in a child array you need to use childConditions instead of conditions. To be able to filter with dates they have to be in ISO8601 format and surrounded by square brackets.

I'm missing something.  With the parameter set in Postman the get should return no data but I'm getting results with dates 2014 for example.
....../v4_6_release/apis/3.0/service/tickets/?childConditions=_info/dateEntered=[1400-01-01T00:00:00Z]

**Comment by rcortez-la** [comment]
> > > The same service/tickets. Our tenant has a few additional have lastUpdated, updatedBy, dateEntered, enteredBy. I'm a rooky with CW, and maybe these are unique on this tenant. What I'm looking for is the created date of the ticket. I was told by the business owner dateEntered is the field I need.
> > 
> > 
> > My bad I totally missed the root _info in the API response last night. I just tested this in Postman and should work. The following conditions worked for me: `_info/dateEntered > [2016-08-20T18:04:26Z]`
> > In the ConnectWise Manage API you can access sub-object attributes with the syntax of subobject/attribute. If the attribute is in a child array you need to use childConditions instead of conditions. To be able to filter with dates they have to be in ISO8601 format and surrounded by square brackets.
> 
> I'm missing something. With the parameter set in Postman the get should return no data but I'm getting results with dates 2014 for example. ....../v4_6_release/apis/3.0/service/tickets/?childConditions=_info/dateEntered=[1400-01-01T00:00:00Z]

I'm getting better results with ?conditions=_info/dateEntered>[2020-01-01T00:00:00.000Z]  In postman i'm getting some dates in 2019 which is ok for now. 

Thanks for the assist.

**Comment by derpenstiltskin** [comment]
No problem, let me know if you need any other assistance in the future. Just an FYI for anyone else who reads this, in your first of the two messages there you were using childConditions, that would be why it wasn't filtering correctly. _info is an object not an array so you have to use conditions to filter it like in your second one there.
