### ISSUE TITLE
This still working?

### ISSUE THREAD

**Issue by TP-projects** [derpenstiltskin/connectwise-powerbi#3]
The CWManageApiRequest query doesn't seem to be working on my end, tried your script in power bi, using the OpenServiceTicket example you provided and am getting `Expression.Error: We cannot convert the value null to type List.`. Could be doing something wrong on my end, but I know I have access since I can request service/tickets on postman.

**Comment by derpenstiltskin** [comment]
Can you share the query you're using to call CWManageApiRequest?

**Comment by TP-projects** [comment]
```
let 
    OpenServiceTickets = let
        Response = CWManageApiRequest(
            "service/tickets",
            [
                conditions = "closedFlag=false",
                fields = "id,summary,company",
                orderBy = "id asc"                 
            ],
            true)
    in
        Response
in
    OpenServiceTickets
```
    
I'm using the identical one that you gave in the OpenServiceTickets example.

**Comment by TP-projects** [comment]
Trying to isolate the code and see where the issue is occurring, after commenting out the expansion code, it still occurs. This makes me believe that the issue is happening in the pagination loop. Still not sure what's causing it.

```
DataList = List.Generate(
            () => [Response = try @RequestPage(Resource, Query, 1) otherwise null, PageNumber = 1],
            each List.Count([Response]) > 0,
            each [Response = try @RequestPage(Resource, Query, [PageNumber] + 1) otherwise null, PageNumber = [PageNumber] + 1],
            each [Response]
        ),
```

**Comment by derpenstiltskin** [comment]
Sorry for the late response here. I'm leaning towards something is failing in the authentication with the request, whether it be the ClientId, Company, or API keys. Are you able to test the API call with PostMan? If you're not familiar creating a PostMan API request, let me know I can give you a premade PostMan query, to where you just need to fill in the values.

**Comment by TP-projects** [comment]
I have it tested in postman and the calls/authentication works fine; I've also managed to get it working through a web source on power bi but just a single page at a time. For some reason something goes wrong when I try to do it manually through this query though.
